set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER arm-none-eabi-gcc)

set(CPU_FLAGS "-mcpu=cortex-m4 -mthumb")
set(CMAKE_C_FLAGS_INIT "${CPU_FLAGS}")
